/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfac;



/**
 *
 * @author Júlio
 */
public class interface5 extends javax.swing.JFrame {

    /**
     * Creates new form interface2
     */
    public interface5() {
        initComponents();
         setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Estoque1.png"))); // NOI18N
        jButton5.setText("jButton2");
        jButton5.setBorder(null);
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(140, 10, 70, 70);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Clientes.png"))); // NOI18N
        jButton6.setText("jButton3");
        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(210, 3, 75, 77);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Rel.png"))); // NOI18N
        jButton7.setText("jButton1");
        jButton7.setContentAreaFilled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(280, 0, 90, 90);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        jLabel5.setText("2024");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(340, 130, 140, 50);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel2.setText("vendidos:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 250, 200, 100);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel3.setText("Lucro anual:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 180, 260, 100);

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel4.setText("Produtos totais");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(150, 220, 214, 100);

        jButton4.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jButton4.setText("<");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(100, 240, 40, 140);

        jButton3.setText("MENSAL");
        getContentPane().add(jButton3);
        jButton3.setBounds(120, 480, 76, 23);

        jButton2.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jButton2.setText(">");
        getContentPane().add(jButton2);
        jButton2.setBounds(679, 240, 40, 140);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Captura-de-tela-2024-05-08-21495 (1).png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 0, 80, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Captura de tela 2024-05-16 202223.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 110, 640, 360);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Captura de tela 2024-05-08 214701.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 100, 830, 420);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Captura de tela 2024-05-01 193006.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 80, 830, 20);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Captura-de-tela-2024-05-08-23373.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(100, 40, 30, 30);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Captura de tela 2024-05-09 003357.png"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(0, 0, 830, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      int larguraPadrao = 844; // Alar se valor se necessário
    int alturaPadrao = 558;  // Altar se valor se necessário
    interface2 novaJanela = new interface2();
    novaJanela.setSize(larguraPadrao, alturaPadrao);
    novaJanela.setLocationRelativeTo(null);

    
    novaJanela.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int larguraPadrao = 844; // Alar se valor se necessário
    int alturaPadrao = 558;  // Altar se valor se necessário
    interface3 novaJanela = new interface3();
    novaJanela.setSize(larguraPadrao, alturaPadrao);
    novaJanela.setLocationRelativeTo(null);

    
    novaJanela.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
           int larguraPadrao = 844; // Alar se valor se necessário
        int alturaPadrao = 558;  // Altar se valor se necessário
    interface6 novaJanela = new interface6();
    novaJanela.setSize(larguraPadrao, alturaPadrao);
    novaJanela.setLocationRelativeTo(null);

    
    novaJanela.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interface5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interface5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interface5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interface5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interface5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
