/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfac;

import interfac.interface2;
import interfac.interface6;


/**
 *
 * @author Júlio
 */
public class interface3 extends javax.swing.JFrame {

    /**
     * Creates new form interface2
     */
    public interface3() {
        initComponents();
         setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Estoque1.png"))); // NOI18N
        jButton5.setText("jButton2");
        jButton5.setBorder(null);
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(140, 10, 70, 70);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Rel.png"))); // NOI18N
        jButton7.setText("jButton1");
        jButton7.setContentAreaFilled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(210, 0, 90, 90);

        jTextField1.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jTextField1.setText("pesquisar...");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(620, 110, 150, 22);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "Idade", "CPF", "Telefone", "Endereço"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 140, 810, 310);

        jButton4.setText("PEDIDOS");
        getContentPane().add(jButton4);
        jButton4.setBounds(670, 460, 77, 23);

        jButton3.setText("REMOVER");
        getContentPane().add(jButton3);
        jButton3.setBounds(330, 460, 110, 23);

        jButton2.setText("ADICIONAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(150, 460, 93, 23);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Captura-de-tela-2024-05-08-21495 (1).png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 0, 80, 80);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Captura de tela 2024-05-08 214701.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 100, 830, 420);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Captura de tela 2024-05-01 193006.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 80, 830, 20);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Captura-de-tela-2024-05-08-23373.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(100, 40, 30, 30);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Captura de tela 2024-05-09 003357.png"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(0, 0, 830, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int larguraPadrao = 844; // Alar se valor se necessário
    int alturaPadrao = 558;  // Altar se valor se necessário
    interface2 novaJanela = new interface2();
    novaJanela.setSize(larguraPadrao, alturaPadrao);
    novaJanela.setLocationRelativeTo(null);

    
    novaJanela.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
      int larguraPadrao = 844; // Alar se valor se necessário
        int alturaPadrao = 558;  // Altar se valor se necessário
    interface6 novaJanela = new interface6();
    novaJanela.setSize(larguraPadrao, alturaPadrao);
    novaJanela.setLocationRelativeTo(null);

    
    novaJanela.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
              int larguraPadrao = 844; // Alar se valor se necessário
    int alturaPadrao = 558;  // Altar se valor se necessário
     //minijanela3 novaJanela = new minijanela3();/
    //novaJanela.setSize(larguraPadrao, alturaPadrao);/
    //novaJanela.setLocationRelativeTo(null);

    
    //novaJanela.setVisible(true);//
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interface3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interface3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interface3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interface3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new interface3().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
