/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfac;

/**
 *
 * @author Júlio
 */
public class minijanela4 extends javax.swing.JFrame {

    /**
     * Creates new form interface3
     */
    public minijanela4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTextField1.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(102, 80, 410, 30);

        jTextField4.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        getContentPane().add(jTextField4);
        jTextField4.setBounds(135, 230, 380, 30);

        jLabel9.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        jLabel9.setText("QUANTIDADE:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 160, 150, 70);

        jTextField5.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        getContentPane().add(jTextField5);
        jTextField5.setBounds(95, 280, 420, 30);

        jLabel11.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        jLabel11.setText("PREÇO:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 260, 130, 70);

        jLabel6.setFont(new java.awt.Font("Britannic Bold", 0, 36)); // NOI18N
        jLabel6.setText("ADICIONAR PEDIDO NOVO");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 0, 410, 70);

        jLabel10.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        jLabel10.setText("ENDEREÇO: ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 210, 140, 70);

        jButton2.setText("ADICIONAR");
        getContentPane().add(jButton2);
        jButton2.setBounds(190, 330, 170, 40);

        jTextField2.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(123, 130, 390, 30);

        jTextField3.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        getContentPane().add(jTextField3);
        jTextField3.setBounds(155, 180, 360, 30);

        jLabel8.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        jLabel8.setText("PRODUTO:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 110, 120, 70);

        jLabel3.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        jLabel3.setText("CÓDIGO:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 60, 100, 70);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Captura de tela 2024-05-16 202223.png"))); // NOI18N
        jLabel7.setText("jLabel1");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 570, 410);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Captura de tela 2024-05-16 202223.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 570, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(minijanela4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(minijanela4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(minijanela4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(minijanela4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new minijanela4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
